### ISSUE TITLE
Inquiry: Plans for Implementing Other HTTP Methods in ResilientHttpClientService

### ISSUE THREAD

**Issue by dennzimm** [tobiasbrenner/resilient-http-service#1]
I noticed that the current implementation of `ResilientHttpClientService` only includes the `get` method. I would like to inquire about any plans or considerations for implementing other HTTP methods (e.g., `post`, `put`, `patch`, `delete`).

**Comment by tobiasbrenner** [comment]
Hey Dennis. This is on purpose. Having resilience patterns applied to not idempotent http verbs is potential dangerous. That was the reason to just override the get method.
